name: Project Builds
run-name: ${{ github.actor }} is building project on ${{ github.server_url }}
on:
  push:
    branches:
      - main
env:
  PLATFORM: casper
jobs:
  build-binaries:
    runs-on: self-hosted
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Run make
        run: make
      - name: Run test
        run: make check
      - name: Run clean
        run: make clean
      - run: echo "This job's status is ${{ job.status }}."
